### ISSUE TITLE
More instructions required for building gui

### ISSUE THREAD

**Issue by jmakin-godaddy** [derselbst/ANMP#74]
Hi, I'm very keen to hear some more of my favourite N64 classics at high quality. I've enjoyed the small number of opus and flac files I've stumbled across.

The README.md file simply says:
mkdir build && cd build
cmake ..
make

If I follow up with a make install as root, I get the following:

# make install
[ 77%] Built target anmp-internal
[ 81%] Built target anmp
[ 90%] Built target anmp-normalize
[100%] Built target anmp-dump
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib64/libanmp.a
-- Installing: /usr/local/include/anmp/PlaylistFactory.h
-- Installing: /usr/local/include/anmp/types.h
-- Installing: /usr/local/include/anmp/Event.h
-- Installing: /usr/local/include/anmp/Nullable.h
-- Installing: /usr/local/include/anmp/SongInfo.h
-- Installing: /usr/local/include/anmp/IPlaylist.h
-- Installing: /usr/local/include/anmp/Playlist.h
-- Installing: /usr/local/include/anmp/Player.h
-- Installing: /usr/local/include/anmp/Config.h
-- Installing: /usr/local/bin/anmp-normalize
-- Installing: /usr/local/bin/anmp-dump

No gui in the above, but a gui directory is made with its own makefile. Changing to this directory and calling make has no output.
Calling make install in the gui directory produces
Install the project...
-- Install configuration: "RelWithDebInfo"
My linux distro is Fedora 37

**Comment by derselbst** [comment]
Hi, can you pls. provide the full cmake log as well?

**Comment by jmakin-godaddy** [comment]
Ahah, I reran the cmake command and saw useful messages. I had to install qwt-qt5-devel and now i'm making progress

**Comment by jmakin-godaddy** [comment]
I'm also trying to build in support for usf. Between yourself, kode54, joshware, saschaklick and some others I'm a little confused as to whose repos are "authoritative"

**Comment by jmakin-godaddy** [comment]
You have a repo called "lazyusf",  joshware has lazyusf2, both have received updates this year.
The only thing I'm certain of is that audacious-plugin development seems to have died.

**Comment by derselbst** [comment]
It should be fine if you just use libsmf-dev from ubuntu repository.

For lazyusf2 and psflib, you may find some information in the buildlogs as well as the `%build` and `%install` sections of the .spec files in my PPA:
https://build.opensuse.org/project/monitor/home:derselbst:anmp

As you can see, aopsf, psflib, lazyusf2 and vgmstream are currently (only) available on RPM-based distros. So you could use the prebuilt RPMs right away, or download the SRPMs and compile it yourself.

**Comment by jmakin-godaddy** [comment]
I've not been looking for a while, but now I see you have packages built for Fedora. That's fantastic!
