### ISSUE TITLE
error of GPG key for debian 10

### ISSUE THREAD

**Issue by JR-Utily** [derselbst/ANMP#75]
Hello !
I want to test that application, but when I follow instructions from here https://software.opensuse.org/download.html?project=home%3Aderselbst%3Aanmp&package=anmp to get a .deb file, apt won't update because of GPG error ( ` http://download.opensuse.org/repositories/home:/derselbst:/anmp/Debian_10  InRelease : Les signatures suivantes ne sont pas valables : E1307A5825F91BB22AC23E71FC7AEF070EE744C4 ` )
Is it still safe to download and install the file ?

**Comment by JR-Utily** [comment]
Thanks a lot for the reply.

I've managed to install it (by installing the 3 .deb files given in the debian10 folder) and it works well !
I think I will use your app to play ambiant background music during my Tabletop RPG session. It is great !

------- Original Message -------

**Comment by derselbst** [comment]
Glad to hear that you find it useful. I'll keep this issue open as a reminder to have a closer look at the signing keys.

**Comment by derselbst** [comment]
I have generated a new signing key for my build repositories at OBS.

Fingerprint: `e0d4 f4e7 c3aa c138 f17e 1d1c 3d5d 3008 8b3e ee9c`
Key Size: `4096 bytes`
Algorithm type: `RSA`

From now on, as new packages will be built, they will be signed with that new key. RSA 4096 should be considered secure, hence I'm closing this issue.
